---
title: "April 4, 2017  Pre-Class"
date: '2017-04-04'
slug: 04-04-pre-class
---



# April 4, 2017 Pre-Class Assignment

We will have a couple of different things to do before this class. 

## Scheduling an Extra Class

We missed a class due to a snow day. In order to make that up I would like to schedule a class during the week of April 10 - 13. Complete the survey to let me know your availability:

- [When to Meet](https://www.when2meet.com/?6106504-DKqh1)

## Reading

For your week 7 content:

Reading:

- [The SQL Tutorial for Data Analysis](https://community.modeanalytics.com/sql/tutorial/introduction-to-sql/)
- [The SQL Course](http://www.sqlcourse.com/)

## Video Material


- Brown has access to lynda.com. Sign up for your access:
    - [Instructions for Lynda](https://ithelp.brown.edu/kb/articles/440-lynda-com-online-learning)
- Sign into lynda and take the following course:
  - [SQL Essential Training](https://www.lynda.com/SQL-tutorials/SQL-Essential-Training/139988-2.html)

 

COMPLETE THE ENTIRE LYNDA COURSE!!!

 

Once this is done practice the basic statements using:

 - [SQL Try IT](http://www.w3schools.com/sql/)
 
 
THESE MUST BE COMPLETED BY April 4th, 9am. Email the professor your certificate of complettion.  